project:
  type: book
  output-dir: docs
  title: "Cordados"
author: "Margarito Mora Nuñez"
book:
  chapters:
    - index.qmd
format:
  html:
    toc: true
    number-sections: true
    theme:
      - darkly
    highlight: github
  epub:
    toc: true
    number-sections: true
